Config = Config or {}

Config.MaxTakeOut = 10 -- Maximum amount of items you can withdraw at once. 
-- Items that can be purchased by the ambulance personel
Config.ItemShop = { -- The stock resets every script restart but is synced to all players
    {
        label = 'Radio',
        name = "radio",
        price = 0,
        type = "item",
    },
    {
        label = 'Flashlight',
        name = "weapon_flashlight",
        price = 0,
        type = "item",
    },
    {
        label = 'Fire Extinguisher',
        name = "weapon_fireextinguisher",
        price = 0,
        type = "item",
    },
    {
        label = 'Pager',
        name = "pager",
        price = 0,
        type = "item",
    },
    {
        label = 'Bodybag',
        name = "bodybag",
        price = 0,
        type = "item",
    },
    {
        label = 'ECG',
        name = "ecg",
        price = 0,
        type = "item",
        amount = 30,
    },
    {
        label = 'Tourniquet',
        name = "tourniquet",
        price = 0,
        type = "item",
        amount = 300,
    },
    {
        label = 'Field Dressing',
        name = "field_dressing",
        price = 0,
        type = "item",
        amount = 500,
    },
    {
        label = 'Elastic Bandage',
        name = "elastic_bandage",
        price = 0,
        type = "item",
        amount = 500,
    },
    {
        label = 'Quick Clot',
        name = "quick_clot",
        price = 0,
        type = "item",
        amount = 50,
    },
    {
        label = 'Packing Bandage',
        name = "packing_bandage",
        price = 0,
        type = "item",
        amount = 500,
    },
    {
        label = 'Sewing Kit',
        name = "sewing_kit",
        price = 0,
        type = "item",
        amount = 100,
    },
    {
        label = 'Epinephrine',
        name = "epinephrine",
        price = 0,
        type = "item",
        amount = 150,
    },
    {
        label = 'Morphine',
        name = "morphine",
        price = 0,
        type = "item",
        amount = 150,
    },
    {
        label = 'Propofol',
        name = "propofol",
        price = 0,
        type = "item",
        amount = 100,
    },
    {
        label = 'Blood Pack 250ml',
        name = "blood250ml",
        price = 0,
        type = "item",
        amount = 50,
    },
    {
        label = 'Blood Pack 500ml',
        name = "blood500ml",
        price = 0,
        type = "item",
        amount = 30,
    },
    {
        label = 'Saline 250ml',
        name = "saline250ml",
        price = 0,
        type = "item",
        amount = 50,
    },
    {
        label = 'Saline 500ml',
        name = "saline500ml",
        price = 10,
        type = "item",
        amount = 50,
    },
    {
        label = 'Stretcher',
        name = "stretcher",
        price = 0,
        type = "item",
        amount = 50,
    },
    {
        label = 'Wheelchair',
        name = "wheelchair",
        price = 0,
        type = "item",
        amount = 50,
    },
    {
        label = 'Crutch',
        name = "crutch",
        price = 0,
        type = "item",
        amount = 50,
    },
    {
        label = 'IFAK',
        name = "ifak",
        price = 0,
        type = "item",
        amount = 20,
    },
    {
        label = 'Revive Kit',
        name = "revivekit",
        price = 20000,
        type = "item",
        amount = 2,
    },
    {
        label = 'Leg Splint',
        name = "legsplint",
        price = 0,
        type = "item",
        amount = 50,
    },
    {
        label = 'Leg Cast',
        name = "legcast",
        price = 0,
        type = "item",
        amount = 50,
    },
    {
        label = 'Arm Splint',
        name = "armsplint",
        price = 0,
        type = "item",
        amount = 50,
    },
    {
        label = 'Arm Cast',
        name = "armcast",
        price = 0,
        type = "item",
        amount = 50,
    },
    {
        label = 'Neck Brace',
        name = "neckbrace",
        price = 0,
        type = "item",
        amount = 50,
    },
    {
        label = 'Neck Cast',
        name = "neckcast",
        price = 0,
        type = "item",
        amount = 50,
    },
}